DIR_MODULE_MEMORY-MANAGER		:= memory-manager
DIR_INTERFACE_MEMORY-MANAGER	:= $(DIR_MODULE_MEMORY-MANAGER)
DIR_INTERNAL_MEMORY-MANAGER	:= $(DIR_MODULE_MEMORY-MANAGER)/_internal

SRC_INTERFACE_MEMORY-MANAGER	:= mmanager.c 
SRC_INTERNAL_MEMORY-MANAGER	:= _mm.c _utils.c 

OBJ_MEMORY-MANAGER			:= $(addprefix $(DIR_OBJ)/$(DIR_INTERFACE_MEMORY-MANAGER)/, $(SRC_INTERFACE_MEMORY-MANAGER:.c=.o))
OBJ_MEMORY-MANAGER			+= $(addprefix $(DIR_OBJ)/$(DIR_INTERNAL_MEMORY-MANAGER)/, $(SRC_INTERNAL_MEMORY-MANAGER:.c=.o))

$(DIR_OBJ)/$(DIR_MODULE_MEMORY-MANAGER)/%.o: $(DIR_SRC)/$(DIR_MODULE_MEMORY-MANAGER)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(DEBUGFLAGS) $(INCLUDE_ALL) -I$(DIR_SRC)/$(DIR_MODULE_MEMORY-MANAGER)/_internal -c $< -o $@
