DIR_MODULE_STR-CHANGE		:= str-change
DIR_INTERFACE_STR-CHANGE	:= $(DIR_MODULE_STR-CHANGE)
DIR_INTERNAL_STR-CHANGE	:= $(DIR_MODULE_STR-CHANGE)/_internal

SRC_INTERFACE_STR-CHANGE	:= ft_atoi.c ft_itoa.c ft_split.c 
SRC_INTERNAL_STR-CHANGE	:= 

OBJ_STR-CHANGE			:= $(addprefix $(DIR_OBJ)/$(DIR_INTERFACE_STR-CHANGE)/, $(SRC_INTERFACE_STR-CHANGE:.c=.o))
OBJ_STR-CHANGE			+= $(addprefix $(DIR_OBJ)/$(DIR_INTERNAL_STR-CHANGE)/, $(SRC_INTERNAL_STR-CHANGE:.c=.o))

$(DIR_OBJ)/$(DIR_MODULE_STR-CHANGE)/%.o: $(DIR_SRC)/$(DIR_MODULE_STR-CHANGE)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(DEBUGFLAGS) -I$(DIR_SRC)/$(DIR_MODULE_STR-CHANGE)/_internal $(INCLUDE_ALL) -c $< -o $@
