DIR_MODULE_ERROR		:= error
DIR_INTERFACE_ERROR	:= $(DIR_MODULE_ERROR)
DIR_INTERNAL_ERROR	:= $(DIR_MODULE_ERROR)/_internal

SRC_INTERFACE_ERROR	:= error.c level.c 
SRC_INTERNAL_ERROR	:= 

OBJ_ERROR			:= $(addprefix $(DIR_OBJ)/$(DIR_INTERFACE_ERROR)/, $(SRC_INTERFACE_ERROR:.c=.o))
OBJ_ERROR			+= $(addprefix $(DIR_OBJ)/$(DIR_INTERNAL_ERROR)/, $(SRC_INTERNAL_ERROR:.c=.o))

$(DIR_OBJ)/$(DIR_MODULE_ERROR)/%.o: $(DIR_SRC)/$(DIR_MODULE_ERROR)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(DEBUGFLAGS) -I$(DIR_SRC)/$(DIR_MODULE_ERROR)/_internal $(INCLUDE_ALL) -c $< -o $@
