DIR_MODULE_MICELLANEOUS		:= micellaneous
DIR_INTERFACE_MICELLANEOUS	:= $(DIR_MODULE_MICELLANEOUS)
DIR_INTERNAL_MICELLANEOUS	:= $(DIR_MODULE_MICELLANEOUS)/_internal

SRC_INTERFACE_MICELLANEOUS	:= 
SRC_INTERNAL_MICELLANEOUS	:= 

OBJ_MICELLANEOUS			:= $(addprefix $(DIR_OBJ)/$(DIR_INTERFACE_MICELLANEOUS)/, $(SRC_INTERFACE_MICELLANEOUS:.c=.o))
OBJ_MICELLANEOUS			+= $(addprefix $(DIR_OBJ)/$(DIR_INTERNAL_MICELLANEOUS)/, $(SRC_INTERNAL_MICELLANEOUS:.c=.o))

$(DIR_OBJ)/$(DIR_MODULE_MICELLANEOUS)/%.o: $(DIR_SRC)/$(DIR_MODULE_MICELLANEOUS)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(DEBUGFLAGS) -I$(DIR_SRC)/$(DIR_MODULE_MICELLANEOUS)/_internal $(INCLUDE_ALL) -c $< -o $@
