DIR_MODULE_LINKED-LIST		:= linked-list
DIR_INTERFACE_LINKED-LIST	:= $(DIR_MODULE_LINKED-LIST)
DIR_INTERNAL_LINKED-LIST	:= $(DIR_MODULE_LINKED-LIST)/_internal

SRC_INTERFACE_LINKED-LIST	:= list_manage.c list_info.c 
SRC_INTERNAL_LINKED-LIST	:= 

OBJ_LINKED-LIST			:= $(addprefix $(DIR_OBJ)/$(DIR_INTERFACE_LINKED-LIST)/, $(SRC_INTERFACE_LINKED-LIST:.c=.o))
OBJ_LINKED-LIST			+= $(addprefix $(DIR_OBJ)/$(DIR_INTERNAL_LINKED-LIST)/, $(SRC_INTERNAL_LINKED-LIST:.c=.o))

$(DIR_OBJ)/$(DIR_MODULE_LINKED-LIST)/%.o: $(DIR_SRC)/$(DIR_MODULE_LINKED-LIST)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(DEBUGFLAGS) -I$(DIR_SRC)/$(DIR_MODULE_LINKED-LIST)/_internal $(INCLUDE_ALL) -c $< -o $@
